# Generated by Django 4.1.3 on 2022-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
            ],
        ),
    ]
