# Generated by Django 4.1.3 on 2022-11-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_level_player_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
