name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pip3 install pipenv
      - name: Run the tests
        run: |
          echo 'DJANGO_SECRET_KEY=TESTING' > .env
          pipenv install django
          pipenv run website/manage.py test game

